services:
  db:
    image: postgres:16-alpine
    env_file:
      - backend/.env
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - "./postgres_data/data:/var/lib/postgresql/data"
    container_name: selfit-postgres-db
